name: Build

on:
  push:
    branches:
    - master
    - github-actions

jobs:
  build:
    name: Makefile build ${{ matrix.platform[0] }}-${{ matrix.platform[1] }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: # list from go-ipfs/mk/utils.mk
          - ['windows', '386']
          - ['windows', 'amd64']
          - ['linux', 'arm']
          - ['linux', 'arm64']
          - ['linux', '386']
          - ['linux', 'amd64']
          - ['darwin', '386']
          - ['darwin', 'amd64']
          - ['freebsd', '386']
          - ['freebsd', 'amd64']
          - ['openbsd', '386']
          - ['openbsd', 'amd64']
          - ['netbsd', '386']
          - ['netbsd', 'amd64']
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14.4
        id: go
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: |
          export GONOSUMDB=github.com/jbarthelmes
          make build GOOS=${{ matrix.platform[0] }} GOARCH=${{ matrix.platform[1] }}
      - run: |
          mkdir -p _out
          cp cmd/ipfs/ipfs _out || true
          cp cmd/ipfs/ipfs.exe _out || true
      - uses: actions/upload-artifact@v1
        with:
          name: ipfs-${{ matrix.platform[0] }}-${{ matrix.platform[1] }}
          path: _out
