name: Main
on:
  push:
    branches:
    - master
    - github-actions

jobs:
  build:
    name: make build ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - 'GOOS=windows GOARCH=386'
          - 'GOOS=windows GOARCH=amd64'
          - 'GOOS=linux GOARCH=arm'
          - 'GOOS=linux GOARCH=arm64'
          - 'GOOS=linux GOARCH=386'
          - 'GOOS=linux GOARCH=amd64'
          - 'GOOS=darwin GOARCH=386'
          - 'GOOS=darwin GOARCH=amd64'
          - 'GOOS=freebsd GOARCH=386'
          - 'GOOS=freebsd GOARCH=amd64'
          - 'GOOS=openbsd GOARCH=386'
          - 'GOOS=openbsd GOARCH=amd64'
          - 'GOOS=netbsd GOARCH=386'
          - 'GOOS=netbsd GOARCH=amd64'
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: make build ${{ matrix.platform }}
      - uses: actions/upload-artifact@v1
        with:
          name: ipfs
          path: cmd/ipfs/ipfs