name: Main
on:
  push:
    branches:
    - master
    - github-actions

jobs:
  build:
    name: Makefile build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Make
        run: make build