name: Main
on:
  push:
    branches:
    - master
    - github-actions

jobs:
  build:
    name: make build ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - ['windows', '386']
          - ['windows', 'amd64']
          - ['linux', 'arm']
          - ['linux', 'arm64']
          - ['linux', '386']
          - ['linux', 'amd64']
          - ['darwin', '386']
          - ['darwin', 'amd64']
          - ['freebsd', '386']
          - ['freebsd', 'amd64']
          - ['openbsd', '386']
          - ['openbsd', 'amd64']
          - ['netbsd', '386']
          - ['netbsd', 'amd64']
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: make build GOOS=${{ matrix.platform[0] }} GOARCH=${{ matrix.platform[1] }}
      - run: mkdir -p _out
      - run: cp cmd/ipfs/ipfs{,.exe} _out
      - uses: actions/upload-artifact@v1
        with:
          name: ipfs-${{ matrix.platform[0] }}-${{ matrix.platform[1] }}
          path: _out